ECOM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path 
from . import views

app_name = "shop"

urlpatterns = [ 
            
    
    
    path('statistiques/', views.statistiques, name='statistiques'),         
   
    path('', views.shop, name='shop'),

    path('panier/', views.panier, name='panier'),
    
    path('commande/', views.commande, name='commande'),

    path('update_article/', views.update_article, name='update_article'),

    path('traitement-commande/', views.traitementCommande, name="traitement_commande"),
    
    path('generer-donnees/', views.generer_donnees_aleatoires, name='generer_donnees'),
    
    path('filtre_produit/', views.filtre_produit, name='filtre_produit')
    
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone



class CategorieSocio(models.Model):
    nom_categ = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    
    def __str__(self):
        return self.nom_categ
    
 

class Client(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE, related_name='client')
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=200, null=True)
    nb_enfants = models.IntegerField(default=0)
    CategorieSocio = models.ForeignKey(CategorieSocio, on_delete=models.SET_NULL, null=True, related_name='clients')


    def __str__(self):
        return str(self.name)

    

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.name


class Produit(models.Model):
    Category = models.ForeignKey(Category, on_delete=models.SET_NULL,blank=True, null=True)
    name = models.CharField(max_length=50, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    date_ajout = models.DateTimeField(default=timezone.now)
 
 #affiche les produits sur le site en fonction de la date d'ajout   
    class Meta:
        ordering = ['-date_ajout']

    def __str__(self):
        return self.name 

#si pas d'images
    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url             


class Commande(models.Model):
    client = models.ForeignKey(Client, on_delete=models.SET_NULL,blank=True, null=True)
    date_commande = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=200, null=True, blank=True)
    total_trans = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    

    def __str__(self):
        return str(self.id)  

    @property
    def produit_physique(self):
        """ savoir si nous avons au moins un produit physique"""
        articlecommande = self.commandearticle_set.all()
        physique = any(article.produit.digital==False for article in articlecommande)
        return physique
        
    @property 
    def get_panier_total(self):
        """ prix total des articles dans le panier"""
        articlecommande = self.commandearticle_set.all()
        total = sum([article.get_total for article in articlecommande])
        return total  

    @property
    def get_panier_article(self):
        """ Nombre total des articles dans le panier"""
        articlecommande = self.commandearticle_set.all()
        quantite_total = sum([article.quantite for article in articlecommande])
        return quantite_total


class CommandeArticle(models.Model):
    produit = models.ForeignKey(Produit, on_delete=models.SET_NULL, blank=True, null=True)
    commande = models.ForeignKey(Commande, on_delete=models.SET_NULL, blank=True, null=True)
    quantite = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

#calcul du prix total du produit placé dans le panier en fonction de la quantité choisie
    @property
    def get_total(self):
        total = self.quantite * self.produit.price
        return total


class AddressChipping(models.Model):
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, blank=True, null=True)
    commande = models.ForeignKey(Commande, on_delete=models.SET_NULL, blank=True, null=True)
    addresse = models.CharField(max_length=100, null=True)
    ville = models.CharField(max_length=100, null=True)
    zipcode = models.CharField(max_length=100, null=True)
    date_ajout =  models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.addresse

shop/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
import json
from datetime import datetime
from .utile import commandeAnonyme, data_cookie, panier_cookie
from .models import Category
from django.views.decorators.csrf import csrf_exempt
import random
from django.contrib.auth.models import User
from django.utils import timezone
from faker import Faker
from .models import CategorieSocio, Client, Category, Produit, Commande, CommandeArticle, AddressChipping
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from decimal import Decimal

from django.http import HttpResponse
from django.db.models import Sum, Avg, Count, DecimalField, ExpressionWrapper, F

import matplotlib.pyplot as plt
import numpy as np

@login_required
def statistiques(request):
    # Récupérer les dépenses par catégorie en fonction de la catégorie socioprofessionnelle
    categories = CategorieSocio.objects.all()
    depenses_par_categorie = []
    depense_panier_moyen = []

    for categorie in categories:
        # Calculez les dépenses pour chaque catégorie socioprofessionnelle
        depenses = Commande.objects.filter(client__CategorieSocio=categorie).values_list('total_trans', flat=True)
        depenses_par_categorie.append(sum(depenses))

        # Calculez la dépense moyenne du panier pour chaque catégorie socioprofessionnelle
        nb_commandes = Commande.objects.filter(client__CategorieSocio=categorie).count()
        if nb_commandes > 0:
            depense_moyenne = sum(depenses) / nb_commandes
        else:
            depense_moyenne = 0
        depense_panier_moyen.append(depense_moyenne)

    # Convertir les valeurs Decimal en float
    depenses_par_categorie = [float(d) for d in depenses_par_categorie]
    depense_panier_moyen = [float(d) for d in depense_panier_moyen]

    context = {
        'depenses_par_categorie': depenses_par_categorie,
        'depense_panier_moyen': depense_panier_moyen,
        'categories_labels': [categorie.nom_categ for categorie in categories]
    }

    return render(request, 'shop/statistiques.html', context)

def filtre_produit(request):
    selected_category_id = request.GET.get('category_id')  # Utilisation de 'category_id' pour le champ de clé primaire
    if selected_category_id:
        selected_category = Category.objects.get(id=selected_category_id)
        produits = Produit.objects.filter(Category=selected_category)
    else:
        produits = Produit.objects.all()

    context = {
        'selected_category': selected_category_id,  # Utilisation de 'selected_category_id' au lieu de 'selected_category'
        'produits': produits,
    }
    return render(request, 'shop/filtre_produit.html', context)


def shop(request, *args, **kwargs):
    """ vue principale """

    produits = Produit.objects.all()
    data = data_cookie(request)
    nombre_article = data['nombre_article']

    context = {
        'produits':produits,
        'nombre_article': nombre_article
    }

    return render(request, 'shop/index.html', context)


def panier(request, *args, **kwargs):
    """ panier """
    
    data = data_cookie(request)
    articles = data['articles']
    commande = data['commande']
    nombre_article = data['nombre_article']

    context = {
        'articles':articles,
        'commande':commande,
        'nombre_article':nombre_article
    }

    return render(request, 'shop/panier.html', context)


def commande(request, *args, **kwargs):
    """ Commande """

    data = data_cookie(request)
    articles = data['articles']
    commande = data['commande']
    nombre_article = data['nombre_article']

    context = {
        'articles':articles,
        'commande':commande,
        'nombre_article': nombre_article
    }

    return render(request, 'shop/commande.html', context)    


@csrf_exempt
def update_article(request, *args, **kwargs):

    data = json.loads(request.body)

    produit_id = data['produit_id']

    action = data['action']

    client = request.user.client

    produit = Produit.objects.get(id=produit_id)

    commande, created = Commande.objects.get_or_create(client=client, complete=False)

    commande_article, created = CommandeArticle.objects.get_or_create(commande=commande, produit=produit)

    if action == 'add':

        commande_article.quantite += 1

    if action == 'remove':

        commande_article.quantite -= 1

    commande_article.save()

    if  commande_article.quantite <= 0:

        commande_article.delete()        

    return JsonResponse("Article ajouté", safe=False)


def traitementCommande(request, *args, **kwargs):
   
    transaction_id = datetime.now().timestamp()

    data = json.loads(request.body)

    if request.user.is_authenticated:

        client = request.user.client

        commande, created = Commande.objects.get_or_create(client=client, complete=False)
    else:
        client, commande = commandeAnonyme(request, data)

    total = float(data['form']['total'])

    commande.transaction_id = transaction_id


    if commande.get_panier_total == total:

        commande.complete = True
    commande.save()       

    if commande.produit_physique:

        AddressChipping.objects.create(
            client=client,
            commande=commande,
            addresse = data['shipping']['address'],
            ville=data['shipping']['city'],
            zipcode=data['shipping']['zipcode']
        )

    return JsonResponse("Votre paiement a été effectué avec succès, votre commande est en cours de préparation !", safe=False)



#définir des données aléatoires
fake = Faker()

@staff_member_required  # Décorateur pour restreindre l'accès aux administrateurs uniquement
@login_required  # Décorateur pour restreindre l'accès aux utilisateurs connectés uniquement
def generer_donnees_aleatoires(request):
    if request.method == 'POST':
        # Supprimer toutes les données existantes (si nécessaire)
        AddressChipping.objects.all().delete()
        CommandeArticle.objects.all().delete()
        Commande.objects.all().delete()
        Produit.objects.all().delete()
        Category.objects.all().delete()
        Client.objects.all().delete()
        CategorieSocio.objects.all().delete()
        User.objects.all().delete()

    # Générer les catégories socio-professionnelles
    categories = ['Cadre', 'Retraité', 'Artisan','Employé']
    for categorie in categories:
        CategorieSocio.objects.create(
            nom_categ=categorie,
            description=fake.text()
        )

    # Générer les clients
    for _ in range(10):  # Générer 10 clients par exemple
        username = fake.user_name()
        email = fake.email()
        name = fake.name()
        nb_enfants = random.randint(0, 5)
        categorie_socio = random.choice(CategorieSocio.objects.all())


        Client.objects.create(
            name=name,
            email=email,
            nb_enfants=nb_enfants,
            CategorieSocio=categorie_socio
        )

    # Générer les catégories
    categories = ['Vêtements', 'Alimentaire', 'Jardinage', 'Multimédia']
    for categorie in categories:
        Category.objects.create(
            name=categorie,
            description=fake.text()
        )

    # Générer les produits
    for _ in range(20):  # Générer 20 produits par exemple
        category = random.choice(Category.objects.all())
        name = fake.word()
        price = random.uniform(1, 100)
        digital = random.choice([True, False])
        image = fake.image_url()
        date_ajout = fake.date_time_this_year(before_now=True, after_now=False, tzinfo=timezone.utc)

        Produit.objects.create(
            Category=category,
            name=name,
            price=price,
            digital=digital,
            image=image,
            date_ajout=date_ajout
        )

    # Générer les commandes
    for _ in range(5):  # Générer 5 commandes par exemple
        client = random.choice(Client.objects.all())
        date_commande = fake.date_time_this_year(before_now=True, after_now=False, tzinfo=timezone.utc)
        complete = random.choice([True, False])
        transaction_id = fake.uuid4()
        status = random.choice(['ACCEPTED', 'COMPLETED', 'SUCCESS'])
        total_trans = random.uniform(10, 100)

        commande = Commande.objects.create(
            client=client,
            date_commande=date_commande,
            complete=complete,
            transaction_id=transaction_id,
            status=status,
            total_trans=total_trans
        )

        # Générer les articles de commande
        produits = random.sample(list(Produit.objects.all()), k=random.randint(1, 5))

        for produit in produits:
            quantite = random.randint(1, 10)
            date_added = fake.date_time_between_dates(datetime_start=date_commande, datetime_end=timezone.now(), tzinfo=timezone.utc)

            commande_article = CommandeArticle.objects.create(
                produit=produit,
                commande=commande,
                quantite=quantite,
                date_added=date_added
            )

        # Générer les adresses de livraison
        if complete and commande.produit_physique:
            addresse = fake.street_address()
            ville = fake.city()
            zipcode = fake.zipcode()
            date_ajout = fake.date_time_between_dates(datetime_start=date_commande, datetime_end=timezone.now(), tzinfo=timezone.utc)

            AddressChipping.objects.create(
                client=client,
                commande=commande,
                addresse=addresse,
                ville=ville,
                zipcode=zipcode,
                date_ajout=date_ajout
            )
        return redirect('accueil')  # Rediriger vers la page d'accueil ou une autre page appropriée
    else:

templates/shop/commande.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<br>
<div class="row">
    <div class="col-lg-5">
        <div class="box-element" id='form-wrapper'>
            <form action="" id="form">
            {% csrf_token %}

                <div id="user-info">
                    <p>Informations Personnelles:</p>

                    <div class="form-field">
                        <input type="text" class="form-control" name="name" placeholder="Nom..." required>
                    </div>

                    <div class="form-field">
                        <input type="number" class="form-control" name="nb_enfants" placeholder="NB enfants..." required>
                    </div>

                    <div class="form-field">
                        <input type="text" class="form-control" name="CategorieSocio" placeholder="Categorie Socio Pro..." required>
                    </div>

                    <div class="form-field">
                        <input type="email" class="form-control" name="email" placeholder="Email..." required>
                    </div>

                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Informations d'Expédition:</p>

                    <div class="form-field">
                        <input type="text" class="form-control" name="address" placeholder="address..." required>
                    </div>

                    <div class="form-field">
                        <input type="text" class="form-control" name="city" placeholder="Ville..." required>
                    </div>

                    <div class="form-field">
                        <input type="text" class="form-control" name="state" placeholder="Pays..." required>
                    </div>

                    <div class="form-field">
                        <input type="text" class="form-control" name="zipcode" placeholder="Zip code..." required>
                    </div>

                </div>
                
                <hr>
                <input id="form-button" class="btn w-100 btn-success btn-block" type="submit" value="Continuer">
            </form>

        </div>

        <br>

        <div class="box-element hidden" id="payment-info">
            <small>Option Paypal</small> <br>
        <!-- <center class="bg-info  my-3"> <button onclick="checkout()" class="btn btn-block" >-->
            <button class="btn w-100 btn-success btn-block" id="make-payment">Effectuer le paiement</button>
            
            
        </div>

    </div>



    <div class="col-lg-6">
        <div class="box-element">

            <a class="btn btn-outline-dark" href="{% url 'shop:panier' %}">&#x2190; Retour au panier </a>

            <hr>
            <h3>Recapitulatif de la commande</h3>
            <hr>
        {% for article in articles  %}
        
            <div class="panier-row">
                <div style="flex:2"><img class="row-image" src="{{article.produit.imageUrl}}" alt=""></div>
                <div style="flex:2">{{article.produit.name}}</div>
                <div style="flex:1">€{{article.produit.price}}</div>
                <div style="flex:1">x{{article.quantite}}</div>
            </div>
        {% endfor %}


            <h5>Articles: {{commande.get_panier_article}}</h5>
            <h5>Total: €{{commande.get_panier_total|floatformat:2}}</h5>
            
        </div>
    </div>
</div>


<script type="text/javascript">

    var produitPhysique = '{{commande.produit_physique}}';

    var total = parseFloat('{{commande.get_panier_total}}').toFixed(2);


    if( produitPhysique === 'False'){
        document.getElementById('shipping-info').innerHTML = '';
    }

    if ( user != "AnonymousUser"){
        document.getElementById('user-info').innerHTML = '';
    }

    if ( produitPhysique == "False" && user != "AnonymousUser"){
        document.getElementById('form-wrapper').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden');

    }

    form = document.getElementById('form');
    csrftoken = form.getElementsByTagName('input')[0].value
    console.log('nouveau token', csrftoken);

    form.addEventListener('submit', function(e){
        e.preventDefault();
        console.log('envoi des données ....');
        document.getElementById('form-button').classList.add('hidden');
        document.getElementById('payment-info').classList.remove('hidden');
    })

     document.getElementById('make-payment').addEventListener('click', function(e){
         submitFormData();
     })


    function submitFormData(){
         

        console.log("paiement en cours");

       //var paymentInfo = {
       //     'transaction_id': transactionId,
       //     'status': 'complet'
       // }
        
        var userFormData = {
            'name':null,
            'nb_enfants':null,
            'CategorieSocio': null,
            'email': null,
            'total': total,
        }

        var shippingUserInfo = {
            'address':null,
            'city':null,
            'state':null,
            'zipcode':null,
        }

        if (produitPhysique != "False"){
            shippingUserInfo.address = form.address.value;
            shippingUserInfo.city = form.city.value;
            shippingUserInfo.state = form.state.value;
            shippingUserInfo.zipcode = form.zipcode.value;
        }

        if (user == "AnonymousUser"){
            userFormData.name = form.name.value;
            userFormData.nb_enfants = form.nb_enfants.value;
            userFormData.CategorieSocio = form.CategorieSocio.value;
            userFormData.email = form.email.value;

            console.log(userFormData);
        }

        var url = '/traitement-commande/';

        fetch(url, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            },
            body: JSON.stringify({"form": userFormData, "shipping": shippingUserInfo})
        })

        .then((response) => {
            return response.json();
        })

        .then((data) => {
            console.log('data', data);
            alert('traitement comande terminé');
            panier = {};
            document.cookie = "panier=" + JSON.stringify(panier) + ";domain=;path=/";
            window.location.href = "{% url 'shop:shop' %}";
            });
            
    }
</script>

{% endblock content %}

templates/shop/filtre_produit.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <!-- debut -->
        {% for produit in produits %}
            {% if produit.Category_id == selected_category.id %}
                <div class="col-lg-4">
                    <img class="thumbnail" src="{{ produit.imageUrl }}"/>
                    <div class="box-element product">
                        <h6>{{ produit.name }}</h6>
                        <hr>
                        <button class="btn btn-outline-secondary add-btn update-panier" data-produit="{{ produit.pk }}" data-action="add">
                            Ajouter au panier
                        </button>
                        <a class="btn btn-outline-success" href="#">Voir</a>
                        <h3 style="float: right;">${{ produit.price|floatformat:2 }}</h3>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <!-- fin -->
    </div>
{% endblock content %}

templates/shop/generer_donnees_aleatoires.html
<form method="POST">
    {% csrf_token %}
    <button type="submit">Générer des données aléatoires</button>
</form>

templates/shop/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h2>Bienvenue sur le site e-commerce de GoldenLine</h2>
    <p>Trouvez votre bonheur, vêtements, alimentaire, jardinage, multimédia ...</p>

    <div class="row">
        <!-- debut -->
        {% for produit in produits  %}
    
        <div class="col-lg-4">
            <img class="thumbnail"  src="{{ produit.imageUrl }}"/>
            <div class="box-element product">
                <h6>{{produit.name}}</h6>
                <hr>
                <button class="btn btn-outline-secondary add-btn update-panier" data-produit={{produit.pk}} data-action="add">
                Ajouter au panier</button>
                <a class="btn btn-outline-success" href="#">Voir</a>
                <h3 style="float: right;">€{{produit.price|floatformat:2}}</h3>
            </div>
        </div>
        {% endfor %}
        <!-- fin -->



    </div>

{% endblock content %}

templates/shop/panier.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<br>
<div class="row">
    <div class="col-lg-12">

        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'shop:shop' %}">&#x2190; Continuer vos achats</a>
            <br><br>
            <table class="table">
                <tr>
                    <th><h5>Articles: <strong>{{commande.get_panier_article}}</strong></h5></th>
                    <th><h5>Total: <strong>€{{commande.get_panier_total|floatformat:2}}</strong></h5></th>
                    <th>
                        <a style="float: right; margin:5px" href="{% url 'shop:commande' %}" class="btn btn-success">
                            Commande</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>

        <div class="box-element">

            <div class="panier-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Article</strong></div>
                <div style="flex:1"><strong>Prix</strong></div>
                <div style="flex:1"><strong>Quantité</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>
        {% for article in articles  %}
          
            <div class="panier-row">
                <div style="flex:2"><img class="row-image" src="{{article.produit.imageUrl}}" alt=""></div>
                <div style="flex:2"> {{article.produit.name}}</div>
                <div style="flex:1">€{{article.produit.price|floatformat:2}}</div>
                <div style="flex:1">
                    <p class="quantite">{{article.quantite}}</p>
                    <div class="quantite">
                        <img class="chg-quantite update-panier" data-produit="{{article.produit.id}}" 
                        data-action="add" src="{% static 'images/arrow-up.png' %}" alt="">

                        <img class="chg-quantite update-panier" data-produit="{{article.produit.id}}" 
                        data-action="remove" src="{%  static 'images/arrow-down.png' %}" alt="">
                    </div>
                </div>
                <div style="flex:1">€{{article.get_total}}</div>
            </div>

        {% endfor %}      

        </div>

    </div>
</div>

{% endblock content %}

templates/shop/statistiques.html
<!DOCTYPE html>
<html>
<head>
    <title>Statistiques</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        .chart-container {
            width: 45%;
            display: inline-block;
            padding: 20px;
            box-sizing: border-box;
        }
    </style>
</head>
<body>
    <div class="chart-container">
        <canvas id="depenses-par-categorie-chart"></canvas>
    </div>
    <div class="chart-container">
        <canvas id="depense-panier-moyen-chart"></canvas>
    </div>
    <a class="btn btn-outline-dark" href="{% url 'shop:shop' %}">&#x2190;Retour</a>
    <script>
        // Récupérer les données depuis la vue Django
        var depensesParCategorieData = {{ depenses_par_categorie|safe }};
        var depensePanierMoyenData = {{ depense_panier_moyen|safe }};
        var categoriesLabels = {{ categories_labels|safe }};

        // Créer les graphiques avec Chart.js
        var depensesParCategorieChart = new Chart(document.getElementById('depenses-par-categorie-chart'), {
            type: 'pie',
            data: {
                labels: categoriesLabels,
                datasets: [{
                    label: 'Dépenses par catégorie socioprofessionnelle',
                    data: depensesParCategorieData,
                    backgroundColor: [
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(192, 75, 75, 0.2)',
                        'rgba(192, 192, 75, 0.2)'
                    ],
                    borderColor: [
                        'rgba(75, 192, 192, 1)',
                        'rgba(192, 75, 75, 1)',
                        'rgba(192, 192, 75, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true
            }
        });

        var depensePanierMoyenChart = new Chart(document.getElementById('depense-panier-moyen-chart'), {
            type: 'bar',
            data: {
                labels: categoriesLabels,
                datasets: [{
                    label: 'Dépense moyenne du panier par catégorie socioprofessionnelle',
                    data: depensePanierMoyenData,
                    backgroundColor: 'rgba(192, 75, 75, 0.2)',
                    borderColor: 'rgba(192, 75, 75, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                plugins: {
                    tooltip: {
                        callbacks: {
                            label: function (context) {
                                var value = context.raw;
                                return value.toFixed(2); // Afficher deux décimales
                            }
                        }
                    }
                },
                responsive: true
            }
        });
    </script>
</body>
</html>