ECOM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path 
from . import views

app_name = "shop"

urlpatterns = [ 
            
    
    
    path('statistiques/', views.statistiques, name='statistiques'),         
   
    path('', views.shop, name='shop'),

    path('panier/', views.panier, name='panier'),
    
    path('commande/', views.commande, name='commande'),

    path('update_article/', views.update_article, name='update_article'),

    path('traitement-commande/', views.traitementCommande, name="traitement_commande"),
    
    path('generer-donnees/', views.generer_donnees_aleatoires, name='generer_donnees'),
    
    path('filtre_produit/', views.filtre_produit, name='filtre_produit')
    
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>GoldenLine</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

     <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" 
     integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <script src="https://cdn.cinetpay.com/seamless/main.js"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script defer type="text/javascript">

      user = '{{ request.user }}'

      function getToken(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie != '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = jQuery.trim(cookies[i]);
                  // Cette chaîne de cookie commence-t-elle par le nom que nous voulons ?
                  if (cookie.substring(0, name.length + 1) == (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      var csrftoken = getToken('csrftoken');


      function getCookie(name){
        var cookieArr = document.cookie.split(";");

        // Boucler à travers les éléments du tableau.
        for(var i = 0; i < cookieArr.length; i++) {
          var cookiePair = cookieArr[i].split("=");

          /* Supprimer les espaces vides au début du nom du cookie et 
          comparer avec la chaîne donnée. */
          if(name==cookiePair[0].trim()){
            // Décoder la valeur du cookie et la renvoyer.
            return decodeURIComponent(cookiePair[1]);
          }
        }

        // Return null si non trouvé
        return null;
      }

      var panier = JSON.parse(getCookie('panier'));

      if( panier == undefined){
        panier = {};
        console.log("panier cree");
        document.cookie = "panier=" + JSON.stringify(panier) + ";domain=;path=/";
      }

      console.log('panier', panier);

    </script>

  </head>
  <body>

  <!-- debut navbar  -->

  <nav class="navbar navbar-expand-lg  bg-white">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'shop:shop' %}">GoldenLine</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'shop:shop' %}">Boutique</a>
          </li>
        
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item category-link" href="{% url 'shop:filtre_produit' %}?category_id=1" data-category="Vêtements">Vêtements</a>
              <li><a class="dropdown-item category-link" href="{% url 'shop:filtre_produit' %}?Category_id=2" data-category="Alimentaire">Alimentaire</a>
              <li><a class="dropdown-item category-link" href="{% url 'shop:filtre_produit' %}?Category_id=3" data-category="Multimédia">Multimédia</a>
              <li><a class="dropdown-item category-link" href="{% url 'shop:filtre_produit' %}?Category_id=4" data-category="Jardin">Jardin</a> 
            </ul>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'shop:statistiques' %}">Statistiques</a>
            {% endif %}
          </li>
        </ul>      

<!-- Navigation bar -->
        <div class="form-inline my-2 my-lg-0">

          <a href="https://aurelie4.pythonanywhere.com/admin/" class="btn btn-warning">Connexion</a>

          <a href="{% url 'shop:panier' %}">

            <img id="icon-panier" src="{% static 'images/panier.png' %}" alt="">

          </a>

          <p id="total-panier">{{ nombre_article }}</p>

        </div>

      </div>
    </div>
  </nav>

  <!-- fin navbar -->
    

   
   <div class="container">
   
     {% block content %}
    
    {% endblock content %}

  


    </div>







    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="{% static 'js/panier.js' %}"></script>

  </body>
</html>